config/routes.rb
Rails.application.routes.draw do
  root 'opinions#index'
  resources :users, only: %i[edit update show new create]
  resources :opinions, only: %i[index new create destroy]
  resources :followings, only: %i[create destroy]
  resources :votes, only: %i[create destroy]
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get 'votes', to: 'votes#create'
  get 'votes/:id', to: 'votes#destroy'
end

app/views/sections/_header.html.erb
<header class="position-sticky blue w-100">
    <div class="d-flex flex-column flex-md-row align-items-center mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center text-dark text-decoration-none px-3">
        <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="me-2" viewBox="0 0 118 94" role="img"><path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z" fill="white"></path></svg>
        <span class="fs-3 text-white">ookRec</span>
      </a>

      <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
        <%= link_to logout_path, method: :delete do%>
          <i class="fas fa-sign-out-alt fa-2x text-white pt-2"></i>
        <% end %>
        <a class="py-2 text-dark text-decoration-none text-white" href="https://www.linkedin.com/in/zulfizarabdumurodova/"><i class="fas fa-user-shield fa-2x px-4"></i></a>
      </nav>
    </div>
  </header>

app/views/sections/_own_profile.html.erb
<% if Current.user %>
  <div class="grey">
    <div class="p-4 dark-grey">
      <div class="row g-0">
        <div class="col-md-4">
          <%= left_user_photo %>
        </div>
        <div class="col-md-8">
          <div class="card-body px-1 py-2">
            <h6 class="card-title">
              <%= link_to Current.user.full_name, user_path(Current.user.id), class: "text-white none text-uppercase" %>
            </h6>
          </div>
        </div>
      </div>
    </div>
    <div>
        <div class="d-flex text-center dark-grey">
            <div class="flex-fill">
                <div class="card-body">
                    <h5 class="card-title fw-bold text-white p-0 m-0"><%= Current.user.followings.count %></h5>
                    <p class="card-text text-white p-0 m-0"><small class="light-grey">Following</small></p>
                </div>
            </div>
            <div class="flex-fill">
                <div class="card-body">
                    <h5 class="card-title text-white fw-bold p-0 m-0"><%= Current.user.followers.count %></h5>
                    <p class="card-text text-white p-0 m-0"><small class="light-grey">Followers</small></p>
                </div>
            </div>
        </div>
    </div>

    <div class="d-flex flex-column bd-highlight m-4">
      <div class="p-2 bd-highlight m-2">
        <%= link_to root_path, class: "text-white none" do %>
          <i class="fas fa-home mx-2"></i>  Home
        <% end %>
      </div>
      <div class="p-2 bd-highlight m-2">
        <%= link_to user_path(Current.user.id), class: "text-white none" do %>
          <i class="fas fa-user-circle mx-2"></i>  Profile
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/sections/_registration.html.erb
<div class="welcome text-center">
    <div class="bd-highlight">
        <div class="welcome-border btn">
            <div class="col-12 mx-auto">
                <p class="text-center text-white fw-bold fs-4">Welcome to BookRec👋</p>
                <p class="text-center text-white fw-bold fs-4">Recommend Books to each other and Share your insights about them</p >
            </div>
            <div class="">
                <span><%= link_to 'Log In', sign_in_path, class:"btn btn-outline-light" %></span>
                <span><%= link_to 'Sign Up', new_user_path, class:"btn btn-outline-light" %></span>
            </div>
        </div>
    </div>
</div>

app/views/sections/_user_profile.html.erb
<div>
    <div>
        <div class="row">
            <div class='col-4'>
                <%= right_user_photo %>
            </div>
            <div class="card-body text-center col-8 px-0">
                <span class="card-title link-dark fw-bold text-white fs-5 p-0 m-0"><%= @user.username %></span><br />
                <%= follow_or_unfollow_friend_request(@user) %>
                <span class="card-text"></span>
            </div>
        </div>
    </div>
    <div>
        <div class="row">
            <div class="col-4">
                <div class="card-body">
                    <h5 class="text-center text-white"><%= @user.opinions.count %></h5>
                    <p class="card-text"><small class="text-white">Tweets</small></p>
                </div>
            </div>
            <div class="col-4">
                <div class="card-body">
                    <h5 class="text-center text-white"><%= @user.followings.count %></h5>
                    <p class="card-text"><small class="text-white">Following</small></p>
                </div>
            </div>
            <div class="col-4">
                <div class="card-body">
                    <h5 class="text-center text-white"><%= @user.followers.count %></h5>
                    <p class="card-text"><small class="text-white">Followers</small></p>
                </div>
            </div>
        </div>
    </div>
    <div>
        <div>
            <p class="text-white p-3">FOLLOWED BY</p>
        </div>
    </div>
    <div>
        <%= right_profile(@user) %>
    </div>
</div>

app/views/sections/_who_to_follow.html.erb
<div class="px-2">
    <h4 class="fw-bold text-white text-center border-btm mb-3 pb-1">Who to Follow</h4>
    <%= right_home %>
</div>